- name: create /etc/docker dicectory
  file: path=/etc/docker state=directory
- name: copy dcoker daemon.json
  copy: src=daemon.json dest=/etc/docker/daemon.json
  notify: restart docker

- name: create /etc/docker/certs.d dicectory
  tags: ca
  file: path=/etc/docker/certs.d state=directory
- name: copy ca certificate
  tags: ca
  copy: src={{ item }} dest=/etc/docker/certs.d/
  with_fileglob:
    - 'ca/*'
  notify: restart docker
