- name: donwload docker-binary package
  tags: download
  get_url:
    validate_certs: no
    url: https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/static/stable/{{ ansible_architecture }}/docker-{{ version }}.tgz
    dest: "{{ role_path }}/files/docker-{{ version }}-{{ ansible_architecture }}.tgz"
    mode: 0644
    force: no
    checksum: sha256:{{ x86_64_sha256 }}
  delegate_to: localhost
  when: ansible_architecture == "x86_64"
