- name: unarchive docker package
  #unarchive: src=docker-{{ docker_version }}.tgz dest=/usr/bin/ extra_opts="--strip-components=1" creates=/usr/bin/docker
  unarchive: src=docker-{{ version }}-{{ ansible_architecture }}.tgz dest=/usr/bin/ extra_opts="--strip-components=1"
